export { default as Header1 } from "./Header1"
export { default as Header2 } from "./Header2"
export { default as Header3 } from "./Header3"
export { default as Header4 } from "./Header4"
export { default as Main1 } from "./Main1"
export { default as Main2 } from "./Main2"